[package]
name = "mail-backup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
mlpa = "0.3.0"
tracing = "0.1.40"

[lib]
crate-type = ["dylib"]
